### ISSUE TITLE
No automatic deploy to GitHub Actions

### ISSUE THREAD

**Issue by niccokunzmann** [chrede88/qubt#189]
### What happened?

When I clone the template, then the github actions deployment for github pages does not run automatically.
It would be nice to have this run automatically.

I created two commits:

I had to rename the action because it was not running:
https://github.com/niccokunzmann/services.quelltext.eu/commit/bb2128bc40615287c6ccd466d94350a3f00c341e

Autodeploy from main branch:
https://github.com/niccokunzmann/services.quelltext.eu/commit/21252fead7510f135e7cfb554522cd3d7ee6c33c

So, I wonder if it would be acceptable to change this and also rename this folder:
https://github.com/chrede88/qubtTemplate/tree/main/.github/deploymentWorkflow

### Theme version

v1.5.0

### Hugo version

hugo v0.139.2-770f548b47b39e6f0fd4da1cc80552024e5829e1 linux/amd64 BuildDate=2024-11-23T15:33:51Z VendorInfo=gohugoio

### Which browser are you using?

Firefox, Chrome

**Comment by chrede88** [comment]
This is the expected behavior, not everyone wants to deploy to github pages. The process of is documented on the wiki along side the other documentation: https://github.com/chrede88/qubt/wiki/Deploy

I'll also leave the default deploy to only run on releases, as users might run into Github Action limits if they use a private repo. These are limited to 2000min/month of run time.
The comments in the workflow should (tell me if you disagree) be sufficient to guide the users if they want to make changes.
